INSERT INTO MPA (MPA_NAME)
VALUES ('G');
INSERT INTO MPA (MPA_NAME)
VALUES ('PG');
INSERT INTO MPA (MPA_NAME)
VALUES ('PG-13');
INSERT INTO MPA (MPA_NAME)
VALUES ('R');
INSERT INTO MPA (MPA_NAME)
VALUES ('NC-17');

INSERT INTO GENRE (NAME)
VALUES ('Комедия');
INSERT INTO GENRE (NAME)
VALUES ('Драма');
INSERT INTO GENRE (NAME)
VALUES ('Мультфильм');
INSERT INTO GENRE (NAME)
VALUES ('Триллер');
INSERT INTO GENRE (NAME)
VALUES ('Документальный');
INSERT INTO GENRE (NAME)
VALUES ('Боевик');

/*
INSERT INTO FILMS (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID)
VALUES ('Брат', 'Лучший фильм 1997', 90, '1997-01-01', 4);
INSERT INTO FILMS (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID)
VALUES ('Невезучие', 'Лучший французский', 90, '1981-01-01', 2);
INSERT INTO FILMS (NAME, DESCRIPTION, DURATION, RELEASE_DATE, MPA_ID)
VALUES ('Сибирский цирюльник', 'Лучшая драма', 120, '1998-01-01', 3);

INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES('anton@yandex.ru', 'toxa', 'anton', '1985-01-01');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES('ivan@yandex.ru', 'vano', 'ivan', '1990-01-01');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES('egor@yandex.ru', 'gosha', 'egor', '1995-01-01');*/

